name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3  # Use the latest version

      # Step 2: Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v3  # Use the latest version
        with:
          python-version: '3.9'

      # Step 3: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel  # Install the Vercel CLI globally

      # Step 4: Deploy to Vercel
      - name: Deploy to Vercel
        run: vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.NEW_VERCEL_TOKEN }}  # Use the Vercel token from GitHub Secrets
