name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Replace with the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3  # Use the latest version (v3)

      # Step 2: Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v3  # Use the latest version (v3)
        with:
          python-version: '3.9'

      # Step 3: Deploy to Vercel
      - name: Deploy to Vercel
        run: vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
